# Build & publish docker images
name: Build DevOps toolbox image using Containerfile
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Image
      id: build-image
      run: |
        buildah login --username adathor --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }} docker.io
        buildah bud -t docker.io/adathor/devops-toolbox:latest -f Containerfile 
        buildah push docker.io/adathor/devops-toolbox:latest